spring.application.name=portfolio
spring.datasource.url=jdbc:postgresql://ep-hidden-art-a1w2h383-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_f6s3OzAyjnBI&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update